pipeline {
    agent any
    
    stages {
        stage ('Build Image ') {
            steps {
                script {
                    dockerapp = docker.build ("thandi13/kube-news:${env.BUILD_ID}", '-f ../src/Dockerfile ../kube-news-jenkins/src')
                }
            }
        }
    }
}