
name: CI - CD

on:
  push:
    branches: [ "feature/github_actions_pipeline" ]
  pull_request:
    branches: [ "feature/github_actions_pipeline" ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USER}}
          password: ${{ secrets.DOCKERHUB_PASSWORD}}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            thandi13/kube-news:latest
            thandi13/kube-news:v-GA-${{ github.run_number }}