
name: CI - CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker user authentication 
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USER}}
          password: ${{ secrets.DOCKERHUB_PASSWORD}}
      - name: Build and push the Docker images to Docker Hub 
        uses: docker/build-push-action@v3.1.1
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            thandi13/kube-news:latest
            thandi13/kube-news:v-GA-${{ github.run_number }}
  CD:
    needs: [CI]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Kubeconfig context definition 
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBERNETES_KUBECONFIG }}

      - name: Deploy to Kubernetes test cluster
        uses: Azure/k8s-deploy@v4.3
        with: 
          namespace: kube-news
          images: thandi13/kube-news:v-GA-${{ github.run_number }}
          manifests: |
            k8s/deployment.yaml
          
  